name: auth
description: Authentication package with session storage and auth providers.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_secure_storage: ^9.0.0
  domain:
    path: ../domain
  data:
    path: ../data
  core:
    path: ../core
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
