name: auth
description: Authentication package with session storage and auth providers.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^4.0.0
  flutter_secure_storage: ^9.0.0
  domain:
    path: ../domain
  data:
    path: ../data
  core:
    path: ../core
  notifications:
    path: ../notifications
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  riverpod_generator: ^4.0.0
